<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesPermissionsSeeder extends Seeder
{


    /**
     * Run the database seeds.
     */
    public array $permissions = [
        "legal_entity:read",
        "employee_request:read",
        "employee_request:write",
        "employee_request:approve",
        "employee_request:reject",
        "employee:read",
        "employee:write",
        "employee:details",
        "employee:deactivate",
        'person_emergency_contact:read',
        "division:write",
        'condition:write',
        'observation:write',
        "division:read",
        "division:details",
        "division:activate",
        "division:deactivate",
        "declaration_request:write",
        "declaration_request:sign",
        "declaration_request:approve",
        "declaration_request:reject",
        "declaration_request:read",
        "declaration:read",
        "otp:read",
        "otp:write",
        "dictionary:read",
        "address:read",
        "legal_entity:write",
        "legal_entity:mis_verify",
        "declaration_request_images:read",
        "innm:write",
        "innm:read",
        "innm_dosage:write",
        "innm_dosage:deactivate",
        "innm_dosage:read",
        "medication:write",
        "medication:read",
        "medication:deactivate",
        "drugs:read",
        "medication_request_request:write",
        "medication_request_request:read",
        "medication_request_request:sign",
        "medication_request_request:reject",
        "medication_request:read",
        "medication_request:details",
        "medication_request:reject",
        "medication_request:resend",
        "medication_dispense:write",
        "medication_dispense:read",
        "medication_dispense:process",
        "medication_dispense:reject",
        "person:reset_authentication_method",
        "reimbursement_report:read",
        "bl_user:write",
        "bl_user:read",
        "bl_user:deactivate",
        "user:block",
        "user:unblock",
        "user:request_factor",
        "user:approve_factor",
        "authentication_factor:write",
        "authentication_factor:read",
        "contract_request:create",
        "contract_request:read",
        "contract_request:approve",
        "contract_request:update",
        "contract_request:sign",
        "contract_request:terminate",
        "contract:read",
        "contract:update",
        "contract:terminate",
        "capitation_report:read",
        "client:read",
        "connection:read",
        "connection:write",
        "connection:refresh_secret",
        "connection:delete",
        "job:read",
        "episode:write",
        "episode:read",
        "encounter:write",
        "encounter:cancel",
        "condition:read",
        "encounter:read",
        "observation:read",
        "immunization:read",
        "allergy_intolerance:read",
        "legal_entity:merge",
        "related_legal_entities:read",
        "legal_entity_merge_job:read",
        "service_request:write",
        "service_request:read",
        "service_request:use",
        'immunization:write',
        "patient_summary:read",
        "procedure:write",
        "procedure:cancel",
        "risk_assessment:read",
        "device:read",
        "medication_statement:read",
        "diagnostic_report:read",
        "diagnostic_report:write",
        "diagnostic_report:cancel",
        "care_plan:write",
        "care_plan:read",
        "approval:read",
        "approval:cancel",
        "medical_program_provision:write",
        "medical_program_provision:read",
        "medication_request_admin:read",
        "medication_request_admin:details",
        "medication_dispense_admin:read",
        "license:write",
        "license:read",
        "license:details",
        "medication_request:block",
        "medication_request:unblock",
        "medication_request:block_pharm",
        "medication_request:details_pharm",
        "medication_dispense:read_pharm",
        "clinical_impression:read",
        "rule_engine_rule:write",
        "rule_engine_rule:details",
        "rule_engine_rule:read",
        "medical_event_context:read",
        "medication_registry:write",
        "medication_registry_job:read",
        "diagnoses_group:read",
        "diagnoses_group:write",
        "justification:write",
        "justification:read",
        "episode:practical_monitor",
        "encounter:practical_monitor",
        "observation:practical_monitor",
        "condition:practical_monitor",
        "procedure:practical_monitor",
        "service_request:practical_monitor",
        "immunization:practical_monitor",
        "allergy_intolerance:practical_monitor",
        "care_plan:practical_monitor",
        "diagnostic_report:practical_monitor",
        "medication_request:practical_monitor",
        "medication_dispense:practical_monitor",
        "episode:clinical_monitor",
        "encounter:clinical_monitor",
        "observation:clinical_monitor",
        "condition:clinical_monitor",
        "procedure:clinical_monitor",
        "service_request:clinical_monitor",
        "immunization:clinical_monitor",
        "allergy_intolerance:clinical_monitor",
        "care_plan:clinical_monitor",
        "diagnostic_report:clinical_monitor",
        "medication_request:clinical_monitor",
        "medication_dispense:clinical_monitor",
        "conclusion:write",
        "conclusion:read",
        "party_verification:details",
        "party_verification:write",
        "person_verification:details",
        "person_verification:write",
        'contract:write',
        'person:read',
        'secret:refresh',
        'healthcare_service:read',
        'healthcare_service:write',
        'employee_role:read',
        'employee_role:write',
        'equipment:write',
        'equipment:read',
        'allergy_intolerance:write',

    ];



    public array $roles = [
        'OWNER' => [
            'capitation_report:read',
            'client:read',
            'connection:delete',
            'connection:read',
            'connection:refresh_secret',
            'connection:write',
            'contract:read',
            'contract:write',
            'contract_request:approve',
            'contract_request:create',
            'contract_request:read',
            'contract_request:sign',
            'contract_request:terminate',
            'declaration:read',
            'declaration_request:approve',
            'declaration_request:read',
            'declaration_request:reject',
            'declaration_request:write',
            'division:activate',
            'division:deactivate',
            'division:details',
            'division:read',
            'division:write',
            'employee:deactivate',
            'employee:details',
            'employee:read',
            'employee:write',
            'employee_request:approve',
            'employee_request:read',
            'employee_request:reject',
            'employee_request:write',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'person_verification:details',
            'reimbursement_report:read',
            'related_legal_entities:read',
            'secret:refresh',
            'healthcare_service:read',
            'healthcare_service:write',
            'employee_role:read',
            'employee_role:write',
            'license:details',
            'license:read',
            'license:write',
            'rule_engine_rule:read',
            'party_verification:details',
            'party_verification:write',
        ],
        'ADMIN' => [
            'declaration:read',
            'declaration_request:approve',
            'declaration_request:reject',
            'declaration_request:read',
            'declaration_request:sign',
            'declaration_request:write',
            'capitation_report:read',
            'division:details',
            'division:read',
            'employee:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee_request:read',
            'employee_request:write',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'service_request:read',
            'service_request:use',
            'contract_request:sign',
            'contract_request:create',
            'contract_request:read',
            'contract_request:terminate',
            'contract_request:approve',
            'contract:read',
            'contract:write',
            'healthcare_service:read',
            'healthcare_service:write',
            'employee_role:read',
            'employee_role:write',
            'equipment:write',
            'equipment:read',
            'party_verification:details',
            'party_verification:write',
            'person_verification:details',
            'person_verification:write'
        ],
//        'DOCTOR' => [
//            'declaration:read',
//            'declaration_request:approve',
//            'declaration_request:read',
//            'declaration_request:sign',
//            'declaration_request:write',
//            'division:read',
//            'employee:read',
//            'employee_request:approve',
//            'employee_request:reject',
//            'employee_request:read',
//            'legal_entity:read',
//            'otp:read',
//            'otp:write',
//            'person:read',
//            'person_emergency_contact:read',
//            'patient_summary:read',
//            'encounter:write',
//            'encounter:read',
//            'encounter:cancel',
//            'episode:write',
//            'episode:read',
//            'job:read',
//            'condition:read',
//            'condition:write',
//            'observation:read',
//            'observation:write',
//            'immunization:read',
//            'immunization:write',
//            'allergy_intolerance:read',
//            'allergy_intolerance:write',
//            'medication_statement:read',
//            'medication_statement:write',
//            'device:read',
//            'device:write',
//            'risk_assessment:read',
//            'risk_assessment:write',
//            'medication_dispense:read',
//            'drugs:read',
//            'medication_request:details',
//            'medication_request:read',
//            'medication_request:reject',
//            'medication_request:resend',
//            'medication_request_request:read',
//            'medication_request_request:reject',
//            'medication_request_request:sign',
//            'medication_request_request:write',
//            'diagnostic_report:read',
//            'diagnostic_report:write',
//            'diagnostic_report:cancel',
//            'procedure:read',
//            'procedure:write',
//            'procedure:cancel',
//            'service_request:makeinprogress',
//            'service_request:complete',
//            'service_request:recall',
//            'service_request:cancel',
//            'service_request:write',
//            'service_request:read',
//            'service_request:use',
//            'approval:create',
//            'program_service:read',
//            'medication_administration:read',
//            'medication_administration:write',
//            'healthcare_service:read',
//            'employee_role:read',
//            'person_request:write',
//            'person_request:read',
//            'authentication_method_request:write',
//            'care_plan:write',
//            'care_plan:read',
//            'approval:read',
//            'approval:cancel',
//            'composition:create',
//            'composition:sign',
//            'composition:cancel',
//            'composition:read',
//            'composition:search',
//            'license:read',
//            'clinical_impression:read',
//            'clinical_impression:write',
//            'rule_engine_rule:read',
//            'medical_event_context:read',
//            'person_verification:details',
//            'person_verification:write',
//            'device_definitions:read',
//            'device_request:write',
//            'device_request:read',
//            'device_request:resend',
//            'device_request:revoke',
//        ],
//        "HR" => [
//            'division:activate',
//            'division:deactivate',
//            'division:details',
//            'division:read',
//            'division:write',
//            'employee:deactivate',
//            'employee:details',
//            'employee:read',
//            'employee:write',
//            'employee_request:approve',
//            'employee_request:read',
//            'employee_request:reject',
//            'employee_request:write',
//            'legal_entity:read',
//            'healthcare_service:read',
//            'healthcare_service:write',
//            'employee_role:read',
//            'employee_role:write',
//            'party_verification:details',
//            'party_verification:write'
//        ]
    ];

    public function run(): void
    {

        foreach ($this->permissions as $permission) {
            Permission::create(['name' => $permission]);
        }

        foreach ($this->roles as $role => $permissions) {
            $role = Role::create(['name' => $role]);
            $role->givePermissionTo($permissions);
        }
    }
}
