<?php

declare(strict_types=1);

return [
    'api' => [
        'domain' => env('EHEALTH_API_URL', 'private-anon-cb2ce4f7fc-uaehealthapi.apiary-mock.com'),
        'token' => env('EHEALTH_X_CUSTOM_PSK', 'X-Custom-PSK'),
        'api_key' => env('EHEALTH_API_KEY', ''),
        'callback_prod' => env('EHEALTH_CALBACK_PROD', true),
        'auth_host' => env('EHEALTH_AUTH_HOST', 'https://auth-preprod.ehealth.gov.ua/sign-in'),
        'redirect_uri' => env('EHEALTH_REDIRECT_URI', 'https://openhealths.com/ehealth/oauth'),
        'url_dev' => env('EHEALTH_URL_DEV', 'http://localhost'),
        'auth_ehealth' => env('EHEALTH_CODE_TOKEN', 'user_id_auth_ehealth'),
        'oauth' => [
            'bearer_token' => env('EHEALTH_OAUTH_TOKEN', 'auth_token'),
            'tokens' => env('EHEALTH_OAUTH_TOKENS', '/oauth/tokens'),
            'user' => env('EHEALTH_OAUTH_USER', '/oauth/user'),
            'logout' => env('EHEALTH_OAUTH_LOGOUT', '/auth/logout')
        ],
        'timeout' => 10,
        'queueTimeout' => 60,
        'cooldown' => 300,
        'retries' => 10,
        'page_size' => 300,
    ],

    'auth' => [
        'decay_seconds' => 300,     /* Amount of the seconds to another login attempt */
        'max_login_attempts' => 5   /* Amount of the wrtong attempt before locking out */
    ],

    'capitation_contract_max_period_days' => 366,
    'legal_entity_type' => [
        'PRIMARY_CARE' => [
            'roles' => ['OWNER', 'ADMIN', 'DOCTOR', 'HR', 'ASSISTANT', 'RECEPTIONIST', 'MED_ADMIN', 'LABORANT'],
            //            'positions' => [
            //                'P3', 'P274', 'P93', 'P202', 'P215', 'P159', 'P118', 'P46', 'P54', 'P99', 'P109', 'P96', 'P245', 'P279',
            //                'P63', 'P123', 'P17', 'P62', 'P45', 'P10', 'P74', 'P37', 'P114', 'P127', 'P214', 'P179', 'P156', 'P145',
            //                'P103', 'P115', 'P126', 'P120', 'P268', 'P110', 'P43', 'P130', 'P203', 'P81', 'P273', 'P95', 'P191',
            //                'P42',
            //                'P38', 'P105', 'P23', 'P197', 'P154', 'P65', 'P58', 'P175', 'P61', 'P98', 'P13', 'P177', 'P173', 'P72',
            //                'P256', 'P178', 'P153', 'P212', 'P53', 'P48', 'P7', 'P106', 'P122', 'P52', 'P158', 'P15', 'P22', 'P39',
            //                'P92', 'P112', 'P71', 'P164', 'P170', 'P266', 'P224', 'P270', 'P78', 'P242', 'P160', 'P2', 'P213',
            //                'P152',
            //                'P26', 'P247', 'P192', 'P36', 'P67', 'P181', 'P124', 'P73', 'P228', 'P55', 'P117', 'P249', 'P91', 'P70',
            //                'P231', 'P229', 'P97', 'P167', 'P169', 'P238', 'P149', 'P150', 'P128', 'P64', 'P51', 'P83', 'P44',
            //                'P241',
            //                'P4', 'P50', 'P250', 'P116', 'P185', 'P276', 'P76', 'P40', 'P69', 'P84', 'P82', 'P176', 'P174', 'P278',
            //                'P155', 'P9', 'P257', 'P29', 'P252', 'P243', 'P24', 'P180', 'P166', 'P201', 'P16', 'P200', 'P210',
            //                'P34',
            //                'P272', 'P168', 'P275', 'P194', 'P165', 'P146', 'P151', 'P111', 'P85', 'P265', 'P87', 'P246', 'P6',
            //                'P77',
            //                'P41', 'P204', 'P94', 'P240', 'P79', 'P14', 'P216', 'P32', 'P59', 'P230', 'P1', 'P88', 'P248', 'P172',
            //                'P75', 'P113', 'P196', 'P28', 'P129', 'P206', 'P57', 'P162', 'P35', 'P107', 'P184', 'P68', 'P131',
            //                'P189',
            //                'P211', 'P60', 'P25', 'P56', 'P161', 'P5', 'P89', 'P188', 'P183', 'P100', 'P47', 'P269', 'P66', 'P8',
            //                'P207', 'P255', 'P119', 'P90', 'P86', 'P27', 'P199', 'P108', 'P163', 'P157', 'P277', 'P11'
            //            ],
        ],
    ],
    'rate_limit' => [
        'employee_request' => 20
    ],
    'employee_type' => [
        'OWNER' => [
            'position' => [
                'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P18', 'P19', 'P22', 'P23', 'P24', 'P25', 'P26', 'P32', 'P229',
                'P230', 'P231', 'P232', 'P233', 'P234', 'P235', 'P236', 'P237', 'P238', 'P239', 'P240', 'P247', 'P249', 'P257'
            ]
        ],
        'ADMIN' => [
            'position' => [
                ' P5', 'P6', 'P14', 'P18', 'P19'
            ]
        ],
        'HR' => [
            'position' => ['P14']
        ],
        'ASSISTANT' => [
            'position' => [
                'P17', 'P66', 'P169', 'P170', 'P171', 'P173', 'P174', 'P175', 'P176', 'P177', 'P178', 'P179', 'P180',
                'P181', 'P182', 'P183', 'P184', 'P185', 'P186', 'P187', 'P188', 'P189', 'P190', 'P191', 'P192', 'P193',
                'P194', 'P195', 'P196', 'P197', 'P198', 'P199', 'P200', 'P201', 'P202', 'P203', 'P204', 'P205', 'P206',
                'P207', 'P208', 'P209', 'P210', 'P211', 'P212', 'P213', 'P214', 'P215', 'P216', 'P250', 'P251', 'P252',
                'P253', 'P256',
            ],
            'speciality_type' => [
                'ORTHOPEDIC_DENTISTRY', 'X_RAY_RADIOLOGY', 'SANOLOGY', 'STOMATOLOGY', 'GENERAL_MEDICINE',
                'MEDICAL_CASE_EMERGENCY_MEDICINE', 'PUBLIC_HEALTH_AND_PREVENTIVE_MEDICINE'
            ]
        ],
        'DOCTOR' => [
            'position' => ['P7', 'P8', 'P9', 'P10', 'P11'],
            'speciality_type' => ['FAMILY_DOCTOR', 'PEDIATRICIAN', 'THERAPIST']
        ],
        'LABORANT' => [
            'position' => [
                'P17', 'P170', 'P173', 'P241', 'P242', 'P243', 'P244', 'P251', 'P256', 'P271', 'P272', 'P273', 'P274',
                'P276', 'P277', 'P278', 'P279', 'P281'
            ],
            'speciality_type' => [
                'VIROLOGY', 'MICROBIOLOGY', 'LABORATORY_GENETICS', 'LABORATORY_IMMUNOLOGY', 'CLINICAL_DIAGNOSTIC',
                'PARASITOLOGY', 'BACTERIOLOGY', 'CLINICAL_BIOCHEMISTRY'
            ]
        ],
        'MED_COORDINATOR' => [
            'position' => ['P280']
        ],
        'NHS ADMIN' => [
            'position' => [
                'P27', 'P28', 'P29', 'P30', 'P31', 'P237', 'P238', 'P239',
            ],
        ],
        'RECEPTIONIST' => [
            'position' => ['P15']
        ],
        'MED_ADMIN' => [
            'position' => [
                'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P33', 'P34', 'P35', 'P36', 'P37', 'P38', 'P39',
                'P40', 'P41', 'P42', 'P43', 'P44', 'P45', 'P46', 'P47', 'P48', 'P49', 'P50', 'P51', 'P52', 'P53', 'P54',
                'P55', 'P56', 'P57', 'P58', 'P59', 'P60', 'P61', 'P62', 'P63', 'P64', 'P65', 'P66', 'P67', 'P68', 'P69',
                'P70', 'P71', 'P72', 'P73', 'P74', 'P75', 'P76', 'P77', 'P78', 'P79', 'P80', 'P81', 'P82', 'P83', 'P84',
                'P85', 'P86', 'P87', 'P88', 'P89', 'P90', 'P91', 'P92', 'P93', 'P94', 'P95', 'P96', 'P97', 'P98', 'P99',
                'P100', 'P101', 'P102', 'P103', 'P104', 'P105', 'P106', 'P107', 'P108', 'P109', 'P110', 'P111', 'P112',
                'P113', 'P114', 'P115', 'P116', 'P117', 'P118', 'P119', 'P120', 'P121', 'P122', 'P123', 'P124', 'P125',
                'P126', 'P127', 'P128', 'P129', 'P130', 'P131', 'P132', 'P133', 'P134', 'P135', 'P136', 'P137', 'P138',
                'P139', 'P140', 'P141', 'P142', 'P143', 'P144', 'P145', 'P146', 'P147', 'P148', 'P149', 'P150', 'P151',
                'P152', 'P153', 'P154', 'P155', 'P156', 'P157', 'P158', 'P159', 'P160', 'P161', 'P162', 'P163', 'P164',
                'P165', 'P166', 'P167', 'P228', 'P248', 'P245', 'P258', 'P266', 'P267', 'P268', 'P269', 'P270', 'P1',
                'P2', 'P3', 'P4', 'P5', 'P6', 'P23', 'P24', 'P25', 'P26', 'P32', 'P229', 'P230', 'P231', 'P249', 'P257'
            ]
        ]
    ],

    'doctors_type' => [
        'LABORANT', 'DOCTOR', 'MED_ADMIN', 'ASSISTANT', 'MED_COORDINATOR'
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/583402009/Medical+Events+Dictionaries+and+configurations#legal_entity_encounter_classes
    'legal_entity_encounter_classes' => [
        'PRIMARY_CARE' => ['PHC'],
        'MSP' => ['PHC'],
        'OUTPATIENT' => ['AMB', 'INPATIENT']
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/583402009/Medical+Events+Dictionaries+and+configurations#employee_encounter_classes
    'employee_encounter_classes' => [
        'DOCTOR' => ['PHC'],
        'SPECIALIST' => ['AMB', 'INPATIENT'],
        'ASSISTANT' => ['PHC', 'AMB', 'INPATIENT'],
        'MED_COORDINATOR' => ['AMB']
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/583402009/Medical+Events+Dictionaries+and+configurations#encounter_class_encounter_types
    'encounter_class_encounter_types' => [
        'AMB' => ['service_delivery_location', 'virtual', 'patient_identity', 'field', 'home', 'intervention'],
        'INPATIENT' => ['patient_identity', 'discharge', 'service_delivery_location', 'intervention'],
        'PHC' => ['service_delivery_location', 'virtual', 'home', 'field', 'intervention']
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/583402009/Medical+Events+Dictionaries+and+configurations#legal_entity_%3CLEGAL_ENTITY_TYPE%3E_episode_types
    'legal_entity_episode_types' => [
        'OUTPATIENT' => ['TREATMENT', 'PREVENTION', 'PALLIATIVE_CARE', 'DG', 'REHAB', 'CONDITIONING'],
        'PRIMARY_CARE' => ['TREATMENT', 'PREVENTION', 'PALLIATIVE_CARE', 'PHC'],
        'MSP' => ['TREATMENT', 'PHC', 'PREVENTION', 'PALLIATIVE_CARE'],
        'MSP_PHARMACY' => ['TREATMENT', 'PREVENTION', 'PALLIATIVE_CARE']
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/583402009/Medical+Events+Dictionaries+and+configurations#employee_%3CEMPLOYEE_TYPE%3E_episode_types
    'employee_episode_types' => [
        'SPECIALIST' => ['TREATMENT', 'PREVENTION', 'PALLIATIVE_CARE', 'DG', 'REHAB', 'CONDITIONING'],
        'DOCTOR' => ['TREATMENT', 'PREVENTION', 'PALLIATIVE_CARE', 'PHC'],
        'ASSISTANT' => ['TREATMENT'],
        'MED_COORDINATOR' => ['TREATMENT', 'DG']
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/17999298851/RC_+CSI-1323+_Create+Update+person+request+v2#Validate-person-documents
    'expiration_date_exists' => [
        'NATIONAL_ID', 'COMPLEMENTARY_PROTECTION_CERTIFICATE', 'PERMANENT_RESIDENCE_PERMIT', 'REFUGEE_CERTIFICATE',
        'TEMPORARY_CERTIFICATE', 'TEMPORARY_PASSPORT'
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/17999299028/Person+documents+configurable+parameters#Person-documents-configurable-parameters
    'self_auth_age_document_types' => [
        'COMPLEMENTARY_PROTECTION_CERTIFICATE', 'NATIONAL_ID', 'PASSPORT', 'PERMANENT_RESIDENCE_PERMIT',
        'REFUGEE_CERTIFICATE', 'TEMPORARY_CERTIFICATE', 'TEMPORARY_PASSPORT'
    ],
    'person_legal_capacity_document_types' => [
        'DIVORCE_CERTIFICATE', 'MARRIAGE_CERTIFICATE', 'STATE_REGISTER_EXTRACT', 'COURT_DECISION_LEGAL_CAPACITY',
        'COURT_DECISION_DIVORCE', 'GUARDIANSHIP_DECISION_LEGAL_CAPACITY', 'LEGAL_CAPACITY_DOCUMENT'
    ],
    'person_registration_document_types' => [
        'BIRTH_CERTIFICATE', 'BIRTH_CERTIFICATE_FOREIGN', 'COMPLEMENTARY_PROTECTION_CERTIFICATE', 'NATIONAL_ID',
        'PASSPORT', 'PERMANENT_RESIDENCE_PERMIT', 'REFUGEE_CERTIFICATE', 'TEMPORARY_CERTIFICATE', 'TEMPORARY_PASSPORT'
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/17678041168/Observation+dictionaries+and+configurations#observation_categories-vs-observation_codes
    'observation_category_codes' => [
        'exam' => [
            '29463-7', '8302-2', 'sex', 'weight_under_1_year', '8339-4', '8310-5', '21112-8', '56086-2', '80319-7',
            '82810-3', '8462-4', '8480-6', '8867-4', '9279-1'
        ],
        'vital-signs' => [
            'stature', 'eye_colour', 'hair_color', 'hair_length', 'beard', 'mustache', 'peculiarity', '31044-1', '30525-0'
        ],
        'social-history' => ['clothes', '85658-3', 'covid_vac_groups'],
        'survey' => [
            'APGAR_1', 'APGAR_5', '11884-4', '57722-1', '73773-4', '73771-8', '11638-4', '68496-9', '75859-9', '39156-5',
            '38214-3', '38215-0', '913921', 'PPS', '96761-2'
        ],
        'laboratory' => [
            '94762-2', '94558-4', '94500-6', '94562-6', '94564-2', '94563-4', '4548-4', '29572-5', '38473-5', '48633-2',
            '29575-8', '2762-3', '50106-4', '45207-8', '53166-5', '45216-9', '45211-0', '53175-6', '45197-1', '45199-7',
            '45200-3', '53192-1', '53191-3', '53190-5', '45198-9', '50125-4', '50132-0', '50113-0', '53187-1', '29293-8',
            '20661-5', '53160-8', '38481-8', '50157-7', '3077-5', '42906-8', '75217-0', '92002-5', '92006-6', '47679-6',
            '47799-2', '14743-9', '35571-9', '10331-7', '14578-9', '78014-8', '78015-5', '96636-6', '57290-9', '57291-7',
            '77636-9', '96664-8', '57293-3', '78017-1', '57299-0', '73809-6', '73807-0', '73808-8', '35471-2', '34960-5',
            '98007-8', '45153-4', '102113-8', '103154-1', '80698-4', '29770-5', '59822-7', '92728-5', '29247-4', '96462-7',
            '50544-6', '77349-9', '16703-1', '3520-4', '14978-1', '55805-6', '16419-4', '55806-4', '70211-8', '63557-3',
            '5196-1', '22316-4', '13952-7', '42595-9', '29610-3', '5193-8', '10900-9', '22327-1', '13955-0', '11011-4',
            '11259,-9', '63464-2', '22587-0', '7852-7', '22244-8', '30325-5', '7853-5', '13238-1', '49178-7', '8039-0',
            '22580-5', '94819-0', '94309-2', '2947-0', '6298-4', '1996-8', '2069-3', '3040-3', '15074-8', '2885-2',
            '1751-7', '6768-6', '14631-6', '14629-0', '1798-8', '1742-6', '1920-8', '59826-8', '72903-8', '32673-6',
            '2157-6', '42757-5', '2324-2', '1988-5', '14804-9', '14805-6', '2524-7', '33959-8', '33762-6', '48664-7',
            '5902-2', '6302-4', '34714-6', '3173-2', '27811-9', '11558-4', '11557-6', '11556-8', '1959-6', '29590-7',
            '30246-3', '14647-2'
        ],
        'procedure' => ['65897-1', '65893-0'],
        'therapy' => ['65897-1', '65893-0', '74200-7', '87238-2'],
        'imaging' => ['65897-1', '65893-0']
    ],
    // https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/17678041168/Observation+dictionaries+and+configurations#eHealth%2FLOINC%2Fobservation_codes
    'observation_code_values' => [
        'functions' => ['', 'valueCodeableConcept', ''],
        'structures' => ['', 'valueCodeableConcept', ''],
        'activities' => ['', 'valueCodeableConcept', ''],
        'environmental' => ['', 'valueCodeableConcept', ''],

        'stature' => ['eHealth/stature', 'valueCodeableConcept', ''],
        'eye_colour' => ['eHealth/eye_colour', 'valueCodeableConcept', ''],
        'hair_color' => ['eHealth/hair_color', 'valueCodeableConcept', ''],
        'hair_length' => ['eHealth/hair_length', 'valueCodeableConcept', ''],
        'beard' => ['', 'valueBoolean', ''],
        'mustache' => ['', 'valueBoolean', ''],
        'clothes' => ['', 'valueString', ''],
        'peculiarity' => ['', 'valueString', ''],
        '31044-1' => ['', 'valueString', ''],
        '29463-7' => ['', 'valueQuantity', 'kg'],
        '8302-2' => ['', 'valueQuantity', 'cm'],
        'sex' => ['GENDER', 'valueCodeableConcept', ''],
        '10331-7' => ['eHealth/LOINC/LL360-9', 'valueCodeableConcept', ''], // TBD CR-200
        '14578-9' => ['eHealth/LOINC/LL2419-1', 'valueCodeableConcept', ''], // TBD CR-200
        '14743-9' => ['', 'valueQuantity', 'mmol/L'],
        '39156-5' => ['', 'valueQuantity', 'kg/m2'],
        '4548-4' => ['', 'valueQuantity', '%'],
        '56086-2' => ['', 'valueQuantity', 'cm'],
//         '80319-7' => ['', 'valueCodeableConcept', '], // TBD CR-200
        '82810-3' => ['eHealth/LOINC/LL4129-4', 'valueCodeableConcept', ''], // TBD CR-200
        '8310-5' => ['', 'valueQuantity', 'Cel'],
        '8462-4' => ['', 'valueQuantity', 'mm[Hg]'],
        '8480-6' => ['', 'valueQuantity', 'mm[Hg]'],
        '8867-4' => ['', 'valueQuantity', '{Beats}/min'],
        '9279-1' => ['', 'valueQuantity', '{Breaths}/min'],
        'APGAR_1' => ['0-10', 'valueQuantity', 'ScoreOf'],
        'APGAR_5' => ['0-10', 'valueQuantity', 'ScoreOf'],
        '11884-4' => ['', 'valueQuantity', 'wk'],
        '8339-4' => ['', 'valueQuantity', 'g'],
        '57722-1' => ['', 'valueBoolean', ''],
        '73773-4' => ['1-12', 'valueQuantity', '{#}'],
        '73771-8' => ['1-12', 'valueQuantity', ''],
        '11638-4' => ['0-20', 'valueQuantity', '{#}'],
        '68496-9' => ['0-20', 'valueQuantity', '{#}'],
        'weight_under_1_year' => ['', 'valueQuantity', 'g'],
        '75859-9' => ['eHealth/rankin_scale', 'valueCodeableConcept', ''],
        '94762-2' => ['eHealth/LOINC/LL2009-0', 'valueCodeableConcept', ''],
        '94558-4' => ['eHealth/LOINC/LL2021-5', 'valueCodeableConcept', ''],
        '94500-6' => ['eHealth/LOINC/LL2021-5', 'valueCodeableConcept', ''],
        '94562-6' => ['eHealth/LOINC/LL2009-0', 'valueCodeableConcept', ''],
        '94564-2' => ['eHealth/LOINC/LL2009-0', 'valueCodeableConcept', ''],
        '94563-4' => ['eHealth/LOINC/LL2009-0', 'valueCodeableConcept', ''],
        '85658-3' => ['eHealth/occupation_type', 'valueCodeableConcept', ''],
        '65897-1' => ['0-3', 'valueQuantity', '{#}'],
        '65893-0' => ['0-3', 'valueQuantity', '{#}'],
        '30525-0' => ['0-120', 'valueQuantity', 'a'],
        'covid_vac_groups' => ['eHealth/vaccination_covid_groups', 'valueCodeableConcept', ''],
        '29572-5' => ['0-50', 'valueQuantity', 'mg/dL'],
        '38473-5' => ['0-150', 'valueQuantity', 'ng/mL'],
        '48633-2' => ['0-150', 'valueQuantity', 'ug/L'],
        '29575-8' => ['0-15', 'valueQuantity', 'm[IU]/L'],
        '21112-8' => ['', 'valueDateTime', ''],
        '2762-3' => ['0-10', 'valueQuantity', 'mg/dL'],
        '50106-4' => ['0-1', 'valueQuantity', 'umol/L'],
        '45207-8' => ['0-1', 'valueQuantity', 'umol/L'],
        '53166-5' => ['0-10', 'valueQuantity', 'umol/L'],
        '45216-9' => ['0-10', 'valueQuantity', 'umol/L'],
        '45211-0' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '53175-6' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '45197-1' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '45199-7' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '45200-3' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '53192-1' => ['0-1', 'valueQuantity', 'umol/L'],
        '53191-3' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '53190-5' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '45198-9' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '50125-4' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '50132-0' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '50113-0' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '53187-1' => ['0-0.5', 'valueQuantity', 'umol/L'],
        '29293-8' => ['0-10', 'valueQuantity', 'mg/dL'],
        '20661-5' => ['0-300', 'valueQuantity', 'umol/L'],
        '53160-8' => ['0-5', 'valueQuantity', 'umol/L'],
        '38481-8' => ['0-100', 'valueQuantity', 'umol/L'],
        '50157-7' => ['0-50', 'valueQuantity', 'umol/L'],
        '3077-5' => ['0-10', 'valueQuantity', 'mg/dL'],
        '42906-8' => ['0-100', 'valueQuantity', 'nmol/h/mL'],
        '75217-0' => ['0-0.5', 'valueQuantity', 'nmol/mL/min'],
        '92002-5' => ['0-100', 'valueQuantity', '{Ct_value}'],
        '92006-6' => ['0-100', 'valueQuantity', '{Ct_value}'],
        '47679-6' => ['', 'valueQuantity', 'umol/L'],
        '47799-2' => ['', 'valueQuantity', 'umol/L'],
        '35571-9' => ['0-1000', 'valueQuantity', 'umol/L'],
        '38214-3' => ['1-10', 'valueQuantity', 'ScoreOf'],
        '38215-0' => ['1-10', 'valueQuantity', 'ScoreOf'],
        '91392-1' => ['1-10', 'valueQuantity', 'ScoreOf'],
        '78014-8' => ['', 'valueString', ''],
        '78015-5' => ['', 'valueString', ''],
        '96636-6' => ['', 'valueString', ''],
        '57290-9' => ['', 'valueString', ''],
        '57291-7' => ['', 'valueString', ''],
        '77636-9' => ['', 'valueString', ''],
        '96664-8' => ['', 'valueString', ''],
        '57293-3' => ['', 'valueString', ''],
        '78017-1' => ['', 'valueString', ''],
        '57299-0' => ['', 'valueString', ''],
        '73809-6' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '73807-0' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '73808-8' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '35471-2' => ['eHealth/LOINC/LL360-9', 'valueCodeableConcept', ''],
        '34960-5' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '98007-8' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '45153-4' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '102113-8' => ['', 'valueQuantity', '%'],
        '103154-1' => ['', 'valueQuantity', '%'],
        '80698-4' => ['', 'valueQuantity', '%'],
        '29770-5' => ['', 'valueString', ''],
        '59822-7' => ['', 'valueQuantity', 'ug/L'],
        '92728-5' => ['', 'valueQuantity', 'ug/L'],
        '29247-4' => ['', 'valueQuantity', 'ng/mL'],
        '96462-7' => ['', 'valueQuantity', 'nmol/L'],
        '50544-6' => ['', 'valueQuantity', 'ng/mL'],
        '77349-9' => ['', 'valueQuantity', 'ng/mL'],
        '16703-1' => ['', 'valueQuantity', 'ng/mL'],
        '3520-4' => ['', 'valueQuantity', 'ng/mL'],
        '14978-1' => ['', 'valueQuantity', 'ug/L'],
        '55805-6' => ['', 'valueQuantity', 'ug/L'],
        '16419-4' => ['', 'valueQuantity', 'ng/mL'],
        '55806-4' => ['', 'valueQuantity', 'mg/L'],
        '70211-8' => ['', 'valueQuantity', 'umol/L'],
        '63557-3' => ['', 'valueQuantity', '[IU]/L'],
        '5196-1' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '22316-4' => ['', 'valueQuantity', "[arb'U]/mL"],
        '13952-7' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '42595-9' => ['', 'valueQuantity', '[IU]/mL'],
        '29610-3' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '5193-8' => ['', 'valueQuantity', 'm[IU]/mL'],
        '10900-9' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '22327-1' => ['', 'valueQuantity', '[IU]/mL'],
        '13955-0' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '11011-4' => ['', 'valueQuantity', '[IU]/mL'],
        '11259-9' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '63464-2' => ['', 'valueQuantity', '{index_val}'],
        '22587-0' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '7852-7' => ['', 'valueQuantity', '[IU]/mL'],
        '22244-8' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '30325-5' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '7853-5' => ['', 'valueQuantity', '[IU]/mL'],
        '13238-1' => ['', 'valueQuantity', '[IU]/mL'],
        '49178-7' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '8039-0' => ['', 'valueQuantity', '[IU]/mL'],
        '22580-5' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '94819-0' => ['', 'valueQuantity', '{copies}/mL'],
        '94309-2' => ['eHealth/LOINC/LL3250-9', 'valueCodeableConcept', ''],
        '2947-0' => ['', 'valueQuantity', 'mmol/L'],
        '6298-4' => ['', 'valueQuantity', 'mmol/L'],
        '1996-8' => ['', 'valueQuantity', 'mmol/L'],
        '2069-3' => ['', 'valueQuantity', 'mmol/L'],
        '3040-3' => ['', 'valueQuantity', 'U/L'],
        '15074-8' => ['', 'valueQuantity', 'mmol/L'],
        '2885-2' => ['', 'valueQuantity', 'g/dL'],
        '1751-7' => ['', 'valueQuantity', 'g/dL'],
        '6768-6' => ['', 'valueQuantity', 'U/L'],
        '14631-6' => ['', 'valueQuantity', 'umol/L'],
        '14629-0' => ['', 'valueQuantity', 'umol/L'],
        '1798-8' => ['', 'valueQuantity', 'U/L'],
        '1742-6' => ['', 'valueQuantity', 'U/L'],
        '1920-8' => ['', 'valueQuantity', 'U/L'],
        '59826-8' => ['', 'valueQuantity', 'umol/L'],
        '72903-8' => ['', 'valueQuantity', 'umol/L'],
        '32673-6' => ['', 'valueQuantity', 'U/L'],
        '2157-6' => ['', 'valueQuantity', 'U/L'],
        '42757-5' => ['', 'valueQuantity', 'ng/mL'],
        '2324-2' => ['', 'valueQuantity', 'U/L'],
        '1988-5' => ['', 'valueQuantity', 'mg/L'],
        '14804-9' => ['', 'valueQuantity', 'U/L'],
        '14805-6' => ['', 'valueQuantity', 'U/L'],
        '2524-7' => ['', 'valueQuantity', 'mmol/L'],
        '33959-8' => ['', 'valueQuantity', 'ng/mL'],
        '33762-6' => ['', 'valueQuantity', 'pg/mL'],
        '48664-7' => ['', 'valueQuantity', 'g/L'], // деактивовано
        '5902-2' => ['', 'valueQuantity', 's'],
        '6302-4' => ['', 'valueQuantity', '%'],
        '34714-6' => ['', 'valueQuantity', '{INR}'],
        '3173-2' => ['', 'valueQuantity', 's'],
        '27811-9' => ['', 'valueQuantity', '%'],
        '11558-4' => ['', 'valueQuantity', '[pH]'],
        '11557-6' => ['', 'valueQuantity', 'mm[Hg]'],
        '11556-8' => ['', 'valueQuantity', 'mm[Hg]'],
        '1959-6' => ['', 'valueQuantity', 'mmol/L'],
        '29590-7' => ['', 'valueQuantity', 'pg/mL'],
        '30246-3' => ['eHealth/LOINC/LL2451-4', 'valueCodeableConcept', ''],
        '14647-2' => ['', 'valueQuantity', 'mmol/L'],
        'PPS' => ['0-100', 'valueQuantity', '%'],
        '74200-7' => ['', 'valueQuantity', 'day'],
        '87238-2' => ['', 'valueString', ''],
        '96761-2' => ['0-100', 'valueQuantity', 'ScoreOf']
    ],

    // Set the test environment
    'test' => [
        'client_id' => env('TEST_CLIENT_ID'),
        'client_secret' => env('TEST_CLIENT_SECRET'),
        'emails' => env('TEST_CLIENT_EMAILS') ? explode(',', env('TEST_CLIENT_EMAILS')) : [],
    ],

    'roles' => [
        'OWNER' => [
            'capitation_report:read',
            'client:read',
            'connection:delete',
            'connection:read',
            'connection:refresh_secret',
            'connection:write',
            'contract:read',
            'contract:write',
            'contract_request:approve',
            'contract_request:create',
            'contract_request:read',
            'contract_request:sign',
            'contract_request:terminate',
            'declaration:read',
            'declaration_request:approve',
            'declaration_request:read',
            'declaration_request:reject',
            'declaration_request:write',
            'division:activate',
            'division:deactivate',
            'division:details',
            'division:read',
            'division:write',
            'employee:deactivate',
            'employee:details',
            'employee:read',
            'employee:write',
            'employee_request:approve',
            'employee_request:read',
            'employee_request:reject',
            'employee_request:write',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'person_verification:details',
            'reimbursement_report:read',
            'related_legal_entities:read',
            'secret:refresh',
            'healthcare_service:read',
            'healthcare_service:write',
            'employee_role:read',
            'employee_role:write',
            'license:details',
            'license:read',
            'license:write',
            'rule_engine_rule:read',
            'party_verification:details',
            'party_verification:write',
        ],
        'ADMIN' => [
            'declaration:read',
            'declaration_request:approve',
            'declaration_request:reject',
            'declaration_request:read',
            'declaration_request:sign',
            'declaration_request:write',
            'capitation_report:read',
            'division:details',
            'division:read',
            'employee:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee_request:read',
            'employee_request:write',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'service_request:read',
            'service_request:use',
            'contract_request:sign',
            'contract_request:create',
            'contract_request:read',
            'contract_request:terminate',
            'contract_request:approve',
            'contract:read',
            'contract:write',
            'healthcare_service:read',
            'healthcare_service:write',
            'employee_role:read',
            'employee_role:write',
            'equipment:write',
            'equipment:read',
            'party_verification:details',
            'party_verification:write',
            'person_verification:details'
        ],
        'DOCTOR' => [
            'declaration:read',
            'declaration_request:approve',
            'declaration_request:read',
            'declaration_request:sign',
            'declaration_request:write',
            'division:read',
            'employee:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee_request:read',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'person_emergency_contact:read',
            'patient_summary:read',
            'encounter:write',
            'encounter:read',
            'encounter:cancel',
            'episode:write',
            'episode:read',
            'job:read',
            'condition:read',
            'condition:write',
            'observation:read',
            'observation:write',
            'immunization:read',
            'immunization:write',
            'allergy_intolerance:read',
            'allergy_intolerance:write',
            'medication_statement:read',
            'medication_statement:write',
            'device:read',
            'device:write',
            'risk_assessment:read',
            'risk_assessment:write',
            'medication_dispense:read',
            'drugs:read',
            'medication_request:details',
            'medication_request:read',
            'medication_request:reject',
            'medication_request:resend',
            'medication_request_request:read',
            'medication_request_request:reject',
            'medication_request_request:sign',
            'medication_request_request:write',
            'diagnostic_report:read',
            'diagnostic_report:write',
            'diagnostic_report:cancel',
            'procedure:read',
            'procedure:write',
            'procedure:cancel',
            'service_request:makeinprogress',
            'service_request:complete',
            'service_request:recall',
            'service_request:cancel',
            'service_request:write',
            'service_request:read',
            'service_request:use',
            'approval:create',
            'program_service:read',
            'medication_administration:read',
            'medication_administration:write',
            'healthcare_service:read',
            'employee_role:read',
            'person_request:write',
            'person_request:read',
            'authentication_method_request:write',
            'care_plan:write',
            'care_plan:read',
            'approval:read',
            'approval:cancel',
            'composition:create',
            'composition:sign',
            'composition:cancel',
            'composition:read',
            'composition:search',
            'license:read',
            'clinical_impression:read',
            'clinical_impression:write',
            'rule_engine_rule:read',
            'medical_event_context:read',
            'person_verification:details',
            'person_verification:write',
            'device_definition:read',
            'device_request:write',
            'device_request:read',
            'device_request:resend',
            'device_request:revoke',
            'specimen:write',
            'specimen:read',
            'specimen:process',
            'specimen:cancel',
            'specimen:reject',
            'specimen:invalidate',
            'device_request:mark_in_error',
            'device_request:complete',
            'device_dispense:read',
            'device_association:read',
            'detected_issue:read',
            // Only preprod
            'composition:write',
            'composition:mark_in_error',
            'composition:resend_sms',
            'composition_configuration:read',
            'person_verification:read',
            'confidant_person_relationship_request:write',
            'confidant_person_relationship:read'
        ],
        'HR' => [
            'division:activate',
            'division:deactivate',
            'division:details',
            'division:read',
            'division:write',
            'employee:deactivate',
            'employee:details',
            'employee:read',
            'employee:write',
            'employee_request:approve',
            'employee_request:read',
            'employee_request:reject',
            'employee_request:write',
            'legal_entity:read',
            'healthcare_service:read',
            'healthcare_service:write',
            'employee_role:read',
            'employee_role:write',
            'party_verification:details',
            'party_verification:write'
        ],
        'SPECIALIST' => [
            'division:read',
            'employee:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee_request:read',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'patient_summary:read',
            'encounter:write',
            'encounter:read',
            'encounter:cancel',
            'episode:write',
            'episode:read',
            'job:read',
            'condition:read',
            'condition:write',
            'observation:read',
            'observation:write',
            'immunization:read',
            'immunization:write',
            'allergy_intolerance:read',
            'allergy_intolerance:write',
            'medication_statement:read',
            'medication_statement:write',
            'device:read',
            'device:write',
            'risk_assessment:read',
            'risk_assessment:write',
            'medication_dispense:read',
            'drugs:read',
            'medication_request:details',
            'medication_request:read',
            'medication_request:reject',
            'medication_request:resend',
            'medication_request_request:read',
            'medication_request_request:reject',
            'medication_request_request:sign',
            'medication_request_request:write',
            'diagnostic_report:read',
            'diagnostic_report:write',
            'diagnostic_report:cancel',
            'procedure:read',
            'procedure:write',
            'procedure:cancel',
            'service_request:makeinprogress',
            'service_request:complete',
            'service_request:recall',
            'service_request:cancel',
            'service_request:write',
            'service_request:read',
            'service_request:use',
            'approval:create',
            'program_service:read',
            'medication_administration:read',
            'medication_administration:write',
            'healthcare_service:read',
            'employee_role:read',
            'person_request:write',
            'person_request:read',
            'preperson:read',
            'preperson:write',
            'authentication_method_request:write',
            'merge_request:write',
            'merge_request:sign',
            'merge_request:read',
            'composition:create',
            'composition:search',
            'composition:read',
            'composition:sign',
            'composition:cancel',
            'care_plan:write',
            'care_plan:read',
            'approval:read',
            'approval:cancel',
            'license:read',
            'clinical_impression:read',
            'rule_engine_rule:read',
            'medical_event_context:read',
            'clinical_impression:write',
            'person_verification:details',
            'person_verification:write',
            'person_emergency_contact:read',
            'device_definition:read',
            'device_request:write',
            'device_request:read',
            'device_request:resend',
            'device_request:revoke',
        ],
        'ASSISTANT' => [
            'division:read',
            'employee:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee_request:read',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'person_emergency_contact:read',
            'patient_summary:read',
            'diagnostic_report:read',
            'diagnostic_report:write',
            'diagnostic_report:cancel',
            'procedure:read',
            'procedure:write',
            'procedure:cancel',
            'service_request:makeinprogress',
            'service_request:complete',
            'service_request:read',
            'service_request:use',
            'care_plan:read',
            'approval:create',
            'healthcare_service:read',
            'employee_role:read',
            'person_request:write',
            'person_request:read',
            'preperson:read',
            'preperson:write',
            'job:read',
            'observation:write',
            'allergy_intolerance:write',
            'medication_statement:write',
            'device:write',
            'risk_assessment:write',
            'medication_administration:write',
            'authentication_method_request:write',
            'merge_request:write',
            'merge_request:read',
            'immunization:read',
            'observation:read',
            'approval:read',
            'approval:cancel',
            'episode:read',
            'episode:write',
            'encounter:write',
            'encounter:read',
            'encounter:cancel',
            'immunization:write',
            'condition:write',
            'condition:read',
            'clinical_impression:read',
            'rule_engine_rule:read',
            'license:read',
            'medication_request_request:read',
            'medication_request:read',
            'medication_request:details',
            'medication_dispense:read',
            'medication_request:resend',
            'medical_event_context:read',
            'person_verification:details',
            'person_verification:write',
            'device_definition:read',
            'device_request:read',
            'device_request:resend',
        ],
        'LABORANT' => [
            'employee_request:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee:read',
            'employee_role:read',
            'diagnostic_report:write',
            'diagnostic_report:read',
            'diagnostic_report:cancel',
            'service_request:read',
            'service_request:makeinprogress',
            'service_request:use',
            'service_request:complete',
            'division:read',
            'legal_entity:read',
            'job:read',
            'observation:read',
            'observation:write',
        ],
        'RECEPTIONIST' => [
            'declaration:read',
            'declaration_request:approve',
            'declaration_request:reject',
            'declaration_request:read',
            'declaration_request:sign',
            'declaration_request:write',
            'capitation_report:read',
            'division:details',
            'division:read',
            'employee:read',
            'employee_request:approve',
            'employee_request:reject',
            'legal_entity:read',
            'otp:read',
            'otp:write',
            'person:read',
            'service_request:read',
            'service_request:use',
            'approval:create',
            'healthcare_service:read',
            'employee_role:read',
            'person_request:read',
            'preperson:read',
            'preperson:write',
            'authentication_method_request:write',
            'merge_request:write',
            'merge_request:read',
            'job:read',
            'observation:write',
            'allergy_intolerance:write',
            'medication_statement:write',
            'device:write',
            'risk_assessment:write',
            'medication_administration:write',
            'medical_event_context:read',
            'person_verification:details',
        ],
        'MED_ADMIN' => [
            'diagnostic_report:read',
            'diagnostic_report:cancel',
            'encounter:read',
            'encounter:cancel',
            'episode:read',
            'procedure:read',
            'procedure:cancel',
            'person:read',
            'preperson:read',
            'patient_summary:read',
            'division:read',
            'employee:read',
            'legal_entity:read',
            'job:read',
            'condition:read',
            'observation:read',
            'allergy_intolerance:read',
            'risk_assessment:read',
            'immunization:read',
            'medication_request_request:read',
            'medication_request:read',
            'medication_request:details',
            'medication_request:resend',
            'medication_request:reject',
            'medication_dispense:read',
            'medication_request_request:reject',
            'clinical_impression:read',
            'device_request:read',
            'device_request:resend',
            'device_request:revoke',
        ],
        'MED_COORDINATOR' => [
            'employee_request:read',
            'employee_request:approve',
            'employee_request:reject',
            'employee_role:read',
            'diagnostic_report:read',
            'encounter:write',
            'encounter:read',
            'encounter:cancel',
            'episode:write',
            'episode:read',
            'procedure:read',
            'person:read',
            'preperson:read',
            'otp:read',
            'otp:write',
            'person_request:write',
            'person_request:read',
            'authentication_method_request:write',
            'merge_request:write',
            'merge_request:sign',
            'merge_request:read',
            'patient_summary:read',
            'division:read',
            'employee:read',
            'legal_entity:read',
            'job:read',
            'condition:read',
            'condition:write',
            'observation:read',
            'allergy_intolerance:read',
            'risk_assessment:read',
            'immunization:read',
            'clinical_impression:read',
            'service_request:read',
            'service_request:write',
            'service_request:cancel',
            'medication_request:details',
            'medication_request:read',
            'medication_request:reject',
            'medication_request:resend',
            'medication_request_request:read',
            'medication_request_request:reject',
            'medication_request_request:sign',
            'medication_request_request:write',
            'care_plan:read',
            'care_plan:write',
            'approval:read',
            'approval:cancel',
            'approval:create',
            'person_verification:details',
            'person_verification:write',
        ]
    ],

    'emailers' => [
        'credentialsQueueTimeout' => 60,
        'failCredentialsTries' => 3
    ]
];
